#%RAML 1.0 DataType

displayName: Account balance

type: object
properties:
  getAccountBalanceReq:
    type: object
    required: true
    properties:
      Header:
        type: object
        required: true
        properties:
          AccountName:
            type: string
        
              
            required: true
          ReferenceNumber?:
            type: string
            minLength: 5
            
            
      Body:
        type: object
        required:  true
        properties:
          AcctNums:
            type: array


            
            required: true
            

            
            

    
