#%RAML 1.0 Library
usage: common examples


types:
  account-balance-request: !include ../examples/balance-enquiry-request.json
  account-balance-response:  !include ../examples/balance-enquiry-response.json
