#%RAML 1.0 Library
usage: common data type
types:
  account-balance-request: !include ../datatypes/balance-enquiry-request.raml
  fund-transfer-request: !include  ../datatypes/fundtransfer-request.raml
 
  
  
